version: "3.9"

services:
  graphqlgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphqlgo-app
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: norimorienair4614
      DB_NAME: gestion_documentos
      DB_SSLMODE: disable
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pruebas-graphql

networks:
  pruebas-graphql:
    driver: bridge
