name: Go CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: norimorienair4614
          POSTGRES_DB: gestion_documentos
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d gestion_documentos"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build project
        run: go build ./...
